#include <stdio.h>
#include "cell.h"

// Prototype for yyparse (generated by Bison)
int yyparse();

int main()
{
    printf("Cellular Automaton Simulation\n");
    printf("Enter your commands:\n");
    yyparse(); // Call the parser generated by Bison
    return 0;
}
